"""Custom Dynamo backend for inspecting the raw GraphModule.

torch.compile(backend=fn) calls fn(gm, sample_inputs) where gm is the
Dynamo-level GraphModule (pre-AOTAutograd, raw from symbolic_convert).
fn must return a callable that takes positional args and produces the
function's result.

This script defines a minimal inspection backend and walks each captured
gm through THREE different views of the same computation:

  1. gm.graph         — the DAG (fx.Graph) that compilers analyze
  2. gm._code         — the Python source string that recompile() generated
  3. gm.forward       — the exec()'d Python function that actually runs

It also dumps a node-by-node breakdown so the relationship between op /
target / args is concrete.

Compare with:
  - prototypes/v2_aot_api.py    — sees the POST-AOT graph (after
                                  aot_autograd + functionalization +
                                  decomposition).
  - prototypes/v2_aot_boundaries.py — covers boundary cases on post-AOT.

This script sees the PRE-AOT graph (closer to user's Python, more
diversity of node forms: call_method, .shape access, etc.).
"""

import torch


# ---------------------------------------------------------------------------
# Inspection backend — captures every gm Dynamo hands to it
# ---------------------------------------------------------------------------
class InspectBackend:
    """A pytorch backend callable that records every gm it sees."""

    def __init__(self):
        self.gms = []
        self.sample_inputs = []

    def __call__(self, gm: torch.fx.GraphModule, sample_inputs):
        self.gms.append(gm)
        self.sample_inputs.append([
            f"{type(x).__name__}{getattr(x, 'shape', '')}" for x in sample_inputs
        ])
        # Return gm.forward unchanged — let it run normally
        return gm.forward


# ---------------------------------------------------------------------------
# Pretty-printer for one gm
# ---------------------------------------------------------------------------
def inspect_gm(gm, label, sample_inputs_desc):
    """Print all three faces of a GraphModule plus a node-level breakdown."""
    print(f"\n{'=' * 78}")
    print(f"  CASE: {label}")
    print(f"  sample_inputs: {sample_inputs_desc}")
    print(f"{'=' * 78}")

    # ---- Face 1: the DAG ----
    print("\n--- [1] gm.graph (DAG — what compilers analyze) ---")
    print(gm.graph)

    # ---- Face 2: the generated source ----
    print("\n--- [2] gm._code (Python source generated by recompile()) ---")
    print(gm._code)

    # ---- Face 3: the live callable ----
    print("--- [3] gm.forward (exec'd Python function — what runs at call) ---")
    forward = gm.forward
    print(f"  type                  : {type(forward).__name__}")
    print(f"  __qualname__          : {forward.__qualname__}")
    print(f"  __code__.co_filename  : {forward.__code__.co_filename}")
    print(f"  __code__.co_firstlineno: {forward.__code__.co_firstlineno}")

    # ---- Node-level breakdown ----
    print("\n--- [4] Node-by-node breakdown ---")
    print(f"  {'op':<14} {'name':<14} {'target':<35} args")
    print(f"  {'-'*14} {'-'*14} {'-'*35} {'-'*30}")
    for n in gm.graph.nodes:
        target_repr = (
            n.target.__name__ if callable(n.target) and hasattr(n.target, "__name__")
            else str(n.target)
        )
        args_repr = str(n.args)
        if len(args_repr) > 50:
            args_repr = args_repr[:47] + "..."
        print(f"  {n.op:<14} {n.name:<14} {target_repr:<35} {args_repr}")


# ---------------------------------------------------------------------------
# Demo: manually invoke recompile to show graph -> source -> forward
# ---------------------------------------------------------------------------
def demo_recompile_mechanism():
    """Show that gm.graph -> gm._code -> gm.forward is regenerated by
    real_recompile(). Note: Dynamo's gm is a _LazyGraphModule, where
    .recompile() only flags lazy-reset; real_recompile() actually runs
    graph.python_code() and rebinds forward. Plain GraphModule (e.g.
    one you build manually) uses .recompile() directly."""
    print(f"\n{'#' * 78}")
    print("#  Demo: gm.graph -> gm._code -> gm.forward via real_recompile()")
    print(f"{'#' * 78}")

    backend = InspectBackend()

    @torch.compile(backend=backend, dynamic=True)
    def fn(x):
        return x + 1

    fn(torch.randn(3, 4))
    gm = backend.gms[0]

    print(f"\n[gm class] {type(gm).__module__}.{type(gm).__name__}")
    print(f"           (this is why we need real_recompile(), not recompile())")

    print("\n[before any mutation]")
    print(f"  gm.forward id = {id(gm.forward)}")
    print(f"  preview:\n{gm._code}")

    # Manually add an aten.add node before the output
    print("[mutating the graph: insert one more aten.add via fx ops]")
    last_compute = [n for n in gm.graph.nodes
                    if n.op not in ("output", "placeholder")][-1]
    output_node = [n for n in gm.graph.nodes if n.op == "output"][0]
    with gm.graph.inserting_before(output_node):
        new_node = gm.graph.call_function(
            torch.ops.aten.add.Tensor, args=(last_compute, 10)
        )
    output_node.args = ((new_node,),)

    # _LazyGraphModule.real_recompile() short-circuits if forward was
    # already concretized once. Call _real_recompile() (leading underscore)
    # to force an unconditional rebuild from the mutated graph.
    gm._real_recompile()

    print(f"\n[after _real_recompile()]")
    print(f"  gm.forward id = {id(gm.forward)}  (rebuilt)")
    print(f"  preview:\n{gm._code}")


# ---------------------------------------------------------------------------
# Workloads — chosen to surface different node forms
# ---------------------------------------------------------------------------
def case_arithmetic(x):
    """Simple Tensor + int — should emit one call_function aten.add."""
    return x + 1


def case_shape_use(x):
    """x.shape[0] — placeholder is SymInt; floordiv shows up."""
    return x.view(x.shape[0] // 2, 2, -1)


def case_method_chain(x):
    """Method-style calls; should see call_method nodes in Dynamo
    (these get desugared into call_function in the AOT stage)."""
    return x.transpose(0, 1).contiguous()


def case_two_inputs_and_slice(x, y):
    """Slice with sym upper bound; two Tensor inputs."""
    return x[0, :] + y[0, :x.shape[1]]


def case_attention_kernel(q, k):
    """Attention QK pattern; many nodes."""
    B, S, H = q.shape
    n_h = 8
    h_dim = H // n_h
    q2 = q.view(B, S, n_h, h_dim).permute(0, 2, 1, 3)
    k2 = k.view(B, S, n_h, h_dim).permute(0, 2, 3, 1)
    return torch.matmul(q2, k2)


def main():
    cases = [
        ("simple arithmetic: x + 1",         case_arithmetic,        (torch.randn(3, 4),)),
        ("shape-derived: view(shape[0]//2, 2, -1)", case_shape_use,  (torch.randn(8, 6),)),
        ("method chain: transpose + contiguous",  case_method_chain, (torch.randn(3, 4),)),
        ("slice with sym bound: x[0,:] + y[0,:x.shape[1]]",
                                              case_two_inputs_and_slice,
                                              (torch.randn(3, 5), torch.randn(3, 7))),
        ("attention QK",                      case_attention_kernel,
                                              (torch.randn(2, 4, 32), torch.randn(2, 4, 32))),
    ]
    for label, fn, args in cases:
        backend = InspectBackend()
        cfn = torch.compile(fn, backend=backend, dynamic=True)
        cfn(*args)
        if not backend.gms:
            print(f"\n[{label}] no graph captured (likely graph break)")
            continue
        inspect_gm(backend.gms[0], label, backend.sample_inputs[0])

    demo_recompile_mechanism()


if __name__ == "__main__":
    main()
